image: node:10.1.0

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  APP_NAME: blacklight

before_script:
  - ./build.sh
  - npm install

stages:
  - test

test-blacklight:
  stage: test
  script:
    - npm run test
